dbtest/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('studentInfo/<int:sid>/', views.studentInfo, name='studentInfo'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('manager/', views.manager, name='manager'),
    path('manager/classList/', views.classList, name='classList'),
    path('manager/addClass/', views.addClass, name='addClass'),
    path('manager/classStudent/<int:cid>/', views.classStudent, name='classStudent'),
    path('manager/studentList/', views.studentList, name='studentList'),
    path('manager/addStudent/', views.addStudent, name='addStudent'),
    path('manager/deleteStudent/<int:sid>/', views.deleteStudent, name='deleteStudent'),
    path('manager/updateStudent/<int:sid>/', views.updateStudent, name='updateStudent'),
    path('manager/teacherList/', views.teacherList, name='teacherList'),
    path('manager/addTeacher/', views.addTeacher, name='addTeacher'),
    path('manager/deleteTeacher/<int:tid>/', views.deleteTeacher, name='deleteTeacher'),
    path('manager/updateTeacher/<int:tid>/', views.updateTeacher, name='updateTeacher'),
    path('manager/courseList/', views.courseList, name='courseList'),
    path('manager/addCourse/', views.addCourse, name='addCourse'),
    path('manager/deleteCourse/<int:cid>/', views.deleteCourse, name='deleteCourse'),
    path('manager/updateCourse/<int:cid>/', views.updateCourse, name='updateCourse'),
]

mysqltest/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('dbtest/', include('dbtest.urls')),
    path('admin/', admin.site.urls),
]

dbtest/models.py
from django.db import models

# Create your models here.
"""教师表"""
class Teacher(models.Model):
    id = models.IntegerField(primary_key=True)
    password = models.CharField(max_length=20)
    name = models.CharField(max_length=45)

    def __str__(self):
        return self.name


"""班级表"""
class ClassInfo(models.Model):
    id = models.IntegerField(primary_key=True)

    def __str__(self):
        return str(self.id)


"""学生表"""
class Student(models.Model):
    id = models.IntegerField(primary_key=True)
    password = models.CharField(max_length=20)
    name = models.CharField(max_length=45)
    classInfo = models.ForeignKey(ClassInfo, on_delete=models.CASCADE)


"""课程表:同一课名不同老师为不同的课程"""
class Course(models.Model):
    id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=45)
    credit = models.FloatField(default=0)
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE)

    def __str__(self):
        return self.name + "-" + self.teacher.name


"""学生成绩表"""
class StudentCourse(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    score = models.IntegerField(default=0)


"""管理员表"""
class Manager(models.Model):
    id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=45)
    password = models.CharField(max_length=20)

dbtest/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages
from django.http import HttpResponse, Http404
from django.template import loader
from .models import *

# Create your views here.
"""所有学生的信息列表（仅做测试用）"""
def index(request):
    student_list = Student.objects.order_by('id')
    context = {
        'student_list': student_list,
    }
    return render(request, 'dbtest/index.html', context)


"""学号为sid的基本信息和各科成绩"""
def studentInfo(request, sid):
    if not request.COOKIES.get('student'):
        messages.error(request, '请先登录!')
        return redirect('login')
    elif request.COOKIES.get('student') != str(sid):
        messages.error(request, '请先退出当前账号!')
        return redirect('studentInfo', sid=int(request.COOKIES.get('student')))
    student = get_object_or_404(Student, pk=sid)
    score_list = student.studentcourse_set.all()
    context = {
        'student': student,
        'score_list': score_list,
    }
    return render(request, 'dbtest/studentInfo.html', context)


# 以下为正式代码
"""登录界面"""
def login(request):
    if request.method == 'GET':
        return render(request, 'dbtest/login.html')
    id = request.POST['id']
    password = request.POST['password']
    type = request.POST['type']
    if type == 'student':
        person = Student.objects.filter(id=id).first()
    elif type == 'teacher':
        person = Teacher.objects.filter(id=id).first()
    elif type == 'manager':
        person = Manager.objects.filter(id=id).first()
    if not person or person.password != password:
        return render(request, 'dbtest/login.html', {'error_message': '账号或密码错误'})
    # 这里不知道怎么优化能比两次判断类型好点
    if type == 'student':
        req = redirect('studentInfo', sid=id)
        req.set_cookie('student', str(id))
    elif type == 'teacher':
        pass
    elif type == 'manager':
        req = redirect('manager')
        req.set_cookie('manager', str(id))
    return req


"""登出"""
def logout(request):
    req = redirect('login')
    # 此处应有改进
    req.delete_cookie('student')
    req.delete_cookie('manager')
    return req


"""管理员界面"""
def manager(request):
    return render(request, 'dbtest/manager.html')


"""管理员获取班级列表"""
def classList(request):
    class_list = ClassInfo.objects.order_by('id')
    context = { 'classList': class_list, }
    return render(request, 'dbtest/classList.html', context)


"""管理员获取某班所有学生(仅供好看，可以不用）"""
def classStudent(request, cid):
    classInfo = get_object_or_404(ClassInfo, pk=cid)
    return render(request, 'dbtest/classStudent.html', {'classInfo': classInfo})


"""管理员添加班级"""
def addClass(request):
    if request.method == 'GET':
        return render(request, 'dbtest/addClass.html')
    if request.method == 'POST':
        id = int(request.POST['id'])
        if ClassInfo.objects.filter(pk=id):
            return render(request, 'dbtest/addClass.html', {'error_message': "该班级已存在!!!"})
        classInfo = ClassInfo(id=id)
        classInfo.save()
        return render(request, 'dbtest/addClass.html', {'success_message': "添加成功!"})


"""管理员获取学生列表"""
def studentList(request):
    student_list = Student.objects.order_by('id')
    context = {
        'student_list': student_list,
    }
    return render(request, 'dbtest/studentList.html', context)


"""管理员：添加学生"""
def addStudent(request):
    if request.method == 'GET':
        return render(request, 'dbtest/addStudent.html')
    if request.method == 'POST':
        try:
            classInfo = ClassInfo.objects.get(pk=int(request.POST['classInfo']))
        except (KeyError, ClassInfo.DoesNotExist):
            return render(request, 'dbtest/addStudent.html', {'error_message': "不存在此班级!!!"})
        id = int(request.POST['id'])
        if Student.objects.filter(pk=id):
            return render(request, 'dbtest/addStudent.html', {'error_message': "该学号已存在!!!"})
        name = request.POST['name']
        password = request.POST['password']
        newStudent = Student(id=id,classInfo=classInfo,name=name,password=password)
        newStudent.save()
        return render(request, 'dbtest/addStudent.html', {'success_message': "添加成功!"})


"""管理员删除学生"""
def deleteStudent(request, sid):
    student = Student.objects.filter(id=sid)
    if not student:
        messages.error(request, '无效的学生id')
    else:
        student = student[0]
        student.delete()
        messages.success(request, '删除成功')
    return redirect('studentList')


"""管理员修改学生信息"""
def updateStudent(request, sid):
    if request.method == 'GET':
        student = get_object_or_404(Student, id=sid)
        return render(request, 'dbtest/updateStudent.html', {'sid': sid, 'student': student})
    if request.method == 'POST':
        student = get_object_or_404(Student, id=sid)
        id = int(request.POST['id'])
        name, password = request.POST['name'], request.POST['password']
        try:
            classInfo = ClassInfo.objects.get(pk=int(request.POST['classInfo']))
        except (KeyError, ClassInfo.DoesNotExist):
            context = {
                'sid': sid,
                'student': student,
                'error_message': '不存在此班级!!!'
            }
            return render(request, 'dbtest/updateStudent.html', context)
        # 如果要改学号,先判断改动后是否影响别的记录
        if id != sid:
            if Student.objects.filter(pk=id):
                context = {
                    'sid': sid,
                    'student': student,
                    'error_message': '该学号已存在!!!'
                }
                return render(request, 'dbtest/updateStudent.html', context)
        data = { 'id': id, 'classInfo': classInfo, 'name': name, 'password': password }
        Student.objects.filter(pk=sid).update(**data)
        messages.success(request, '修改成功')
        return redirect('studentList')


"""管理员获取老师列表"""
def teacherList(request):
    teacher_list = Teacher.objects.order_by('id')
    return render(request, 'dbtest/teacherList.html', {'teacher_list': teacher_list})


"""管理员：增加老师"""
def addTeacher(request):
    if request.method == 'GET':
        return render(request, 'dbtest/addTeacher.html')
    if request.method == 'POST':
        id = int(request.POST['id'])
        if Teacher.objects.filter(pk=id):
            return render(request, 'dbtest/addTeacher.html', {'error_message': "该工号已存在!!!"})
        name = request.POST['name']
        password = request.POST['password']
        newTeacher = Teacher(id=id, name=name, password=password)
        newTeacher.save()
        return render(request, 'dbtest/addTeacher.html', {'success_message': "添加成功!"})


"""管理员：删除老师"""
def deleteTeacher(request, tid):
    teacher = Teacher.objects.filter(id=tid)
    if not teacher:
        messages.error(request, '无效的教师id')
    else:
        teacher = teacher[0]
        teacher.delete()
        messages.success(request, '删除成功')
    return redirect('teacherList')


"""管理员：修改老师信息"""
def updateTeacher(request, tid):
    if request.method == 'GET':
        teacher = get_object_or_404(Teacher, id=tid)
        return render(request, 'dbtest/updateTeacher.html', {'tid': tid, 'teacher': teacher})
    if request.method == 'POST':
        teacher = get_object_or_404(Teacher, id=tid)
        id = int(request.POST['id'])
        name, password = request.POST['name'], request.POST['password']
        # 如果要改工号,先判断改动后是否影响别的记录
        if id != tid:
            if Teacher.objects.filter(pk=id):
                context = {
                    'tid': tid,
                    'teacher': teacher,
                    'error_message': '该工号已存在!!!'
                }
                return render(request, 'dbtest/updateTeacher.html', context)
        data = {'id': id, 'name': name, 'password': password}
        Teacher.objects.filter(pk=tid).update(**data)
        messages.success(request, '修改成功')
        return redirect('teacherList')


"""管理员：获取课程列表"""
def courseList(request):
    course_list = Course.objects.order_by('id')
    return render(request, 'dbtest/courseList.html', {'course_list': course_list})


"""管理员：增加课程"""
def addCourse(request):
    if request.method == 'GET':
        return render(request, 'dbtest/addCourse.html')
    if request.method == 'POST':
        id = int(request.POST['id'])
        if Course.objects.filter(id=id):
            return render(request, 'dbtest/addCourse.html', {'error_message': "该课程号已存在!!!"})
        tid = int(request.POST['tid'])
        teacher = Teacher.objects.filter(pk=tid).first()
        if not teacher:
            return render(request, 'dbtest/addCourse.html', {'error_message': "该教师不存在!!!"})
        name = request.POST['name']
        credit = float(request.POST['credit'])
        newCourse = Course(id=id, teacher=teacher, name=name, credit=credit)
        newCourse.save()
        return render(request, 'dbtest/addCourse.html', {'success_message': "添加成功!"})


"""管理员：删除课程"""
def deleteCourse(request, cid):
    course = Course.objects.filter(id=cid)
    if not course:
        messages.error(request, '无效的课程id')
    else:
        course = course[0]
        course.delete()
        messages.success(request, '删除成功')
    return redirect('courseList')


"""管理员：修改课程信息"""
def updateCourse(request, cid):
    if request.method == 'GET':
        course = get_object_or_404(Course, id=cid)
        return render(request, 'dbtest/updateCourse.html', {'cid': cid, 'course': course})
    if request.method == 'POST':
        course = get_object_or_404(Course, id=cid)
        try:
            teacher = Teacher.objects.get(id=int(request.POST['tid']))
        except (KeyError, Teacher.DoesNotExist):
            context = {
                'course': course,
                'error_message': "该教工ID不存在!!!"
            }
            return render(request, 'dbtest/updateCourse.html', context)
        id = int(request.POST['id'])
        # 如果要改课程号,先判断改动后是否影响别的记录
        if id != cid:
            if Course.objects.filter(id=cid):
                context = {
                    'cid': cid,
                    'course': course,

dbtest/templates/dbtest/addClass.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>添加班级</title>
</head>
<body>
<h1>添加班级</h1>
<form action="{% url 'addClass' %}" method="post">
    {% csrf_token %}
    <p>班级号：<input type="text" name="id" oninput="value=value.replace(/[^\d]/g,'')"></p>
    <button type="submit" style="color: aquamarine">提交</button>
</form>
<a href="{% url 'classList' %}"><button style="color: lightpink">取消</button> </a>
{% if error_message %}
    <p><strong style="color: firebrick">{{ error_message }}</strong></p>
{% endif %}
{% if success_message %}
    <p><strong style="color: forestgreen">{{ success_message }}</strong></p>
{% endif %}
</body>
</html>

dbtest/templates/dbtest/addCourse.html
{% extends 'dbtest/base.html' %}

{% block title %}
添加课程
{% endblock %}

{% block body %}
<h1>添加课程</h1>
<form action="{% url 'addCourse' %}" method="post">
    {% csrf_token %}
    <p>课程号：<input type="text" name="id" oninput="value=value.replace(/[^\d]/g,'')"></p>
    <p>教工号：<input type="text" name="tid" oninput="value=value.replace(/[^\d]/g,'')"></p>
    <p>课程名：<input type="text" name="name"></p>
    <p>学分：<input type="number" name="credit" step="0.1" value="0.0"></p>
    <button type="submit" style="color: aquamarine">提交</button>
</form>
<a href="{% url 'courseList' %}"><button style="color: lightpink">取消</button> </a>

{% endblock %}

dbtest/templates/dbtest/addStudent.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>AddStudent</title>
</head>
<body>

<h1>添加学生</h1>
<form action="{% url 'addStudent' %}" method="post">
    {% csrf_token %}
    <p>班级：<input type="text" name="classInfo" oninput="value=value.replace(/[^\d]/g,'')"></p>
    <p>学号：<input type="text" name="id" oninput="value=value.replace(/[^\d]/g,'')"></p>
    <p>姓名：<input type="text" name="name"></p>
    <p>密码：<input type="text" name="password"></p>
    <button type="submit" style="color: aquamarine">提交</button>
</form>
<a href="{% url "studentList" %}"><button style="color: lightpink">取消</button> </a>
{% if error_message %}
    <p><strong style="color: firebrick">{{ error_message }}</strong></p>
{% endif %}
{% if success_message %}
    <p><strong style="color: forestgreen">{{ success_message }}</strong></p>
{% endif %}
</body>
</html>

dbtest/templates/dbtest/addTeacher.html
{% extends 'dbtest/base.html' %}

{% block title %}
添加教师
{% endblock %}

{% block body %}
<h1>添加教师</h1>
<form action="{% url 'addTeacher' %}" method="post">
    {% csrf_token %}
    <p>工号：<input type="text" name="id" oninput="value=value.replace(/[^\d]/g,'')"></p>
    <p>姓名：<input type="text" name="name"></p>
    <p>密码：<input type="text" name="password"></p>
    <button type="submit" style="color: aquamarine">提交</button>
</form>
<a href="{% url 'teacherList' %}"><button style="color: lightpink">取消</button> </a>

{% endblock %}

dbtest/templates/dbtest/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
{# 跳转后的弹窗提示 #}
{% if messages %}
{% for message in messages %}
<script type="text/javascript">alert('{{ message }}')</script>
{% endfor %}
{% endif %}

{# 此处可添加导航栏block #}

{# 主体块 #}
{% block body %}
{% endblock %}

{# 页面消息提示 #}
{% if error_message %}
    <p><strong style="color: firebrick">{{ error_message }}</strong></p>
{% endif %}
{% if success_message %}
    <p><strong style="color: forestgreen">{{ success_message }}</strong></p>
{% endif %}

</body>
</html>

dbtest/templates/dbtest/classStudent.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>班级里滴学生</title>
</head>
<body>
<h1>班级{{ classInfo.id }}</h1>
{% if classInfo.student_set.count %}
<table border="1">
    <tr>
        <th>序号</th><th>班级</th><th>学号</th><th>姓名</th><th>密码</th><th>操作</th>
    </tr>
    {% for student in classInfo.student_set.all %}
    <tr>
        <td>{{ forloop.counter }}</td>
        <td>{{ classInfo.id }}</td>
        <td>{{ student.id }}</td>
        <td>{{ student.name }}</td>
        <td>{{ student.password }}</td>
        <td><button>修改</button><button>删除</button></td>
    </tr>
    {% endfor %}
</table>
{% else %}
    <p>班里没得人</p>
{% endif %}
<a href="{% url 'addStudent' %}"><button>添加学生++</button></a>
<br>
<a href="{% url 'classList' %}"><button><strong>返回</strong></button></a>
</body>
</html>

dbtest/templates/dbtest/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Index</title>
</head>
<body>

{% if student_list %}
    <ul>
    {% for student in student_list %}
        <li>{{ student.name }} {{ student.classInfo }}</li>
    {% endfor %}
    </ul>
{% else %}
    <p>No students are available..</p>
{% endif %} 

</body>
</html>

dbtest/templates/dbtest/login.html
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>index</title>
<style type="text/css">
	body{
		background-color:#E4E4E4
	}
	
	div.container{
	width: 370px;
   margin: 100px auto 0px;
   text-align: center;
		
}
	div.header{
		font-family:STHupo;
		font-size:34px;
		color:#745A74;
	}
	input[type=text] {
  width: 360px;
   height: 50px;
   border: none;
   background: #fff;
   border-radius: 10px;
   margin: 5px auto;
   padding-left: 10px;
   color: #745A74;
   font-size: 15px;
}
	input[type=password] {
  width: 360px;
   height: 50px;
   border: none;
   background: #fff;
   border-radius: 10px;
   margin: 5px auto;
   padding-left: 10px;
   color: #745A74;
   font-size: 15px;
}
	.button {
   width: 130px;
   height: 40px;
   background: #745A74;
   border-radius: 10px;
   text-align: center;
   color: #fff;
   margin-top: 30px;
   line-height: 40px;
  }
</style>
</head>
<body>

{% if messages %}
{% for message in messages %}
<script type="text/javascript">alert('{{ message }}')</script>
{% endfor %}
{% endif %}

<div class="container" style="width:500px">
	<div class="header">学生成绩管理系统</div>
	<form name="loginForm" action="{% url 'login' %}" method="post">
		{% csrf_token %}
		用户ID：<br>
		<input type="text" name="id"><br>
		密码：<br>
		<input type="password" name="password"><br>
        {% if error_message %}
            <p><strong style="color: firebrick">{{ error_message }}</strong></p>
        {% endif %}
        <br>
		<input type="radio" name="type" value="student" checked>学生
		<input type="radio" name="type" value="teacher">教师
		<input type="radio" name="type" value="manager">管理员
		<input class="button" type="submit" value="登录">
	</form>
	{{ rlt }}
	</div>
</body>
</html>

dbtest/templates/dbtest/manager.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Manager</title>
</head>
<body>

<div>
    <h1>Welcome 管理员儿~</h1>
    <a href="{% url 'logout' %}"><i><u>登出</u></i></a>
</div>

<ul>
    <li><a href="{% url 'classList' %}">班级列表</a> </li>
    <li><a href="{% url 'studentList' %}">学生列表</a> </li>
    <li><a href="{% url 'teacherList' %}">教师列表</a> </li>
    <li><a href="{% url 'courseList' %}">课程列表</a> </li>
</ul>

</body>
</html>

dbtest/templates/dbtest/studentInfo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>StudentInfo</title>
</head>
<body>

{% if messages %}
{% for message in messages %}
<script type="text/javascript">alert('{{ message }}')</script>
{% endfor %}
{% endif %}

<div>
    <h1>Welcome~{{ student.name }}</h1>
    <a href="{% url 'logout' %}"><i><u>登出</u></i></a>
</div>
<h4>学号：{{ student.id }}      班级：{{ student.classInfo }}</h4>

{% if score_list %}
    <table border="1">
        <tr>
            <th>课程号</th>
            <th>课程名称</th>
            <th>成绩</th>
        </tr>
    {% for score in score_list %}
        <tr>
            <th>{{ score.course.id }} </th>
            <th>{{ score.course }}</th>
            <th>{{ score.score }}</th>
        </tr>
    {% endfor %}
    </table>

{% else %}
    <p>No scores are available!</p>
{% endif %}
</body>
</html>

dbtest/templates/dbtest/teacherList.html
{% extends 'dbtest/base.html' %}

{% block title %}
教师列表
{% endblock %}

{% block body %}

    <h1>教师列表</h1>
{% if teacher_list %}
    <table border="1">
    <tr>
        <th>工号</th><th>姓名</th><th>密码</th><th>操作</th>
    </tr>
    {% for teacher in teacher_list %}
        <tr>
            <td>{{ teacher.id }}</td>
            <td>{{ teacher.name }}</td>
            <td>{{ teacher.password }}</td>
            <td>
                <a href="{% url 'updateTeacher' teacher.id %}"><button>修改</button></a>
                <a href="{% url 'deleteTeacher' teacher.id %}"><button>删除</button></a>
            </td>
        </tr>
    {% endfor %}
    </table>
{% else %}
    <p>No Teachers are available..</p>
{% endif %}

<a href="{% url 'addTeacher' %}"><button><strong>添加教师++</strong></button>
</a>
<br>
<a href="{% url 'manager' %}"><button><strong>返回</strong></button>
</a>

{% endblock %}

dbtest/templates/dbtest/updateCourse.html
{% extends 'dbtest/base.html' %}

{% block title %}
修改课程信息
{% endblock %}

{% block body %}
<h1>修改课程信息</h1>
<form action="{% url 'updateCourse' cid %}" method="post">
    {% csrf_token %}
    <p>教工号：<input type="text" name="id" oninput="value=value.replace(/[^\d]/g,'')" value="{{ course.id }}"></p>
    <p>教工号：<input type="text" name="tid" oninput="value=value.replace(/[^\d]/g,'')" value="{{ course.teacher.id }}"></p>
    <p>课程名：<input type="text" name="name" value="{{ course.name }}"></p>
    <p>学分：<input type="number" step="0.1" name="credit" value="{{ course.credit }}"></p>
    <button type="submit" style="color: aquamarine">提交</button>
</form>
<a href="{% url 'courseList' %}"><button style="color: lightpink">取消</button> </a>

{% endblock %}

dbtest/templates/dbtest/updateStudent.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>修改学生信息</title>
</head>
<body>

<h1>修改学生信息</h1>
<form action="{% url 'updateStudent' sid %}" method="post">
    {% csrf_token %}
    <p>班级：<input type="text" name="classInfo" oninput="value=value.replace(/[^\d]/g,'')" value="{{ student.classInfo.id }}"></p>
    <p>学号：<input type="text" name="id" oninput="value=value.replace(/[^\d]/g,'')" value="{{ student.id }}"></p>
    <p>姓名：<input type="text" name="name" value="{{ student.name }}"></p>
    <p>密码：<input type="text" name="password" value="{{ student.password }}"></p>
    <button type="submit" style="color: aquamarine">提交</button>
</form>
<a href="{% url "studentList" %}"><button style="color: lightpink">取消</button> </a>
{% if error_message %}
    <p><strong style="color: firebrick">失败：{{ error_message }}</strong></p>
{% endif %}

</body>
</html>

dbtest/templates/dbtest/updateTeacher.html
{% extends 'dbtest/base.html' %}

{% block title %}
修改教师信息
{% endblock %}

{% block body %}
<h1>修改教师信息</h1>
<form action="{% url 'updateTeacher' tid %}" method="post">
    {% csrf_token %}
    <p>学号：<input type="text" name="id" oninput="value=value.replace(/[^\d]/g,'')" value="{{ teacher.id }}"></p>
    <p>姓名：<input type="text" name="name" value="{{ teacher.name }}"></p>
    <p>密码：<input type="text" name="password" value="{{ teacher.password }}"></p>
    <button type="submit" style="color: aquamarine">提交</button>
</form>
<a href="{% url "teacherList" %}"><button style="color: lightpink">取消</button> </a>

{% endblock %}